<template>
  <div class="wa-page">
    <div class="wa-header"><div><h2>WhatsApp Bot Transactions</h2><p>Search, review and safely reconcile bot orders.</p></div><button class="btn btn-outline-success" @click="load"><i class="fas fa-sync-alt"></i> Refresh</button></div>
    <div v-if="error" class="alert alert-danger">{{ error }}<br><small>Confirm the WHATSAPP_DB_* connection values on the server.</small></div>
    <div class="summary-grid"><article><span>Total</span><strong>{{ summary.total || 0 }}</strong></article><article><span>In progress</span><strong>{{ summary.pending || 0 }}</strong></article><article><span>Completed</span><strong>{{ summary.completed || 0 }}</strong></article><article><span>Failed/closed</span><strong>{{ summary.failed || 0 }}</strong></article><article><span>Completed value</span><strong>₦{{ money(summary.completed_value) }}</strong></article></div>
    <section class="panel">
      <div class="filters"><input v-model="filters.search" class="form-control" placeholder="Reference, phone or customer…" @keyup.enter="load(1)"><select v-model="filters.status" class="form-control" @change="load(1)"><option value="">All statuses</option><option v-for="status in statuses" :key="status" :value="status">{{ humanize(status) }}</option></select><select v-model="filters.service_type" class="form-control" @change="load(1)"><option value="">All services</option><option v-for="service in serviceTypes" :key="service" :value="service">{{ humanize(service) }}</option></select><button class="btn btn-success" @click="load(1)">Search</button></div>
      <div class="table-responsive"><table class="table table-hover"><thead><tr><th>Reference</th><th>Customer</th><th>Service</th><th>Plan</th><th>Recipient</th><th>Amount</th><th>Payment</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>
        <tr v-for="order in orders.data" :key="order.id"><td><strong>{{ order.ref || shortId(order.id) }}</strong><small>{{ shortId(order.id) }}</small></td><td>{{ customerName(order) }}<small>{{ order.customer ? order.customer.whatsapp_number : '' }}</small></td><td>{{ humanize(order.service_type) }}<small v-if="order.provider_name">{{ order.provider_name }}</small></td><td>{{ order.plan_name || '—' }}</td><td>{{ order.phone_number }}</td><td>₦{{ money(order.amount) }}</td><td><span class="badge" :class="paymentClass(order)">{{ order.payment ? order.payment.status : walletPayment(order) }}</span></td><td><span class="status" :class="statusClass(order.status)">{{ humanize(order.status) }}</span></td><td>{{ date(order.created_at) }}</td><td><button class="btn btn-sm btn-outline-success" @click="openOrder(order)">Manage</button></td></tr>
        <tr v-if="!loading && (!orders.data || !orders.data.length)"><td colspan="10" class="text-center">No WhatsApp transactions found.</td></tr></tbody></table></div>
      <pagination v-if="orders.data" :data="orders" :limit="5" @pagination-change-page="load"></pagination>
    </section>
    <div v-if="selected" class="modal-layer" @click.self="selected = null"><div class="dialog"><button class="close-button" @click="selected = null">×</button><h3>Manage transaction</h3><dl><dt>Reference</dt><dd>{{ selected.ref || selected.id }}</dd><dt>Customer</dt><dd>{{ customerName(selected) }} · {{ selected.customer ? selected.customer.whatsapp_number : '' }}</dd><dt>Service</dt><dd>{{ humanize(selected.service_type) }}<span v-if="selected.provider_name"> / {{ selected.provider_name }}</span></dd><dt>Plan</dt><dd>{{ selected.plan_name || '—' }}</dd><dt>Amount</dt><dd>₦{{ money(selected.amount) }}</dd><dt>Payment</dt><dd>{{ selected.payment ? selected.payment.status : walletPayment(selected) }}</dd></dl><div class="alert alert-warning"><strong>Manual override:</strong> status changes are audited. Use Refund to Wallet for an unsettled transaction that must return value and notify the WhatsApp customer.</div><label>New status</label><select v-model="statusForm.status" class="form-control"><option v-for="status in statuses" :key="status" :value="status">{{ humanize(status) }}</option></select><label>Reason for change or refund</label><textarea v-model="statusForm.note" rows="3" class="form-control" placeholder="Required audit note"></textarea><button class="btn btn-success btn-block mt-3" :disabled="updating || refunding" @click="updateStatus">{{ updating ? 'Updating…' : 'Update Status' }}</button><button v-if="canRefund(selected)" class="btn btn-danger btn-block mt-2" :disabled="updating || refunding" @click="refundOrder">{{ refunding ? 'Refunding…' : 'Refund to Main Wallet & Notify' }}</button></div></div>
  </div>
</template> 

<script>
export default { name: 'WhatsAppTransactionsAdmin', data() { return { summary: {}, orders: { data: [] }, statuses: [], serviceTypes: [], filters: { search: '', status: '', service_type: '' }, selected: null, statusForm: { status: '', note: '' }, loading: false, updating: false, refunding: false, error: '' }; }, mounted() { this.load(); }, methods: {
  load(page) { this.loading = true; this.error = ''; axios.get('/api/admin/whatsapp-transactions', { params: Object.assign({ page: page || 1 }, this.filters) }).then(response => { const data = response.data.data; this.summary = data.summary; this.orders = data.orders; this.statuses = data.statuses; this.serviceTypes = data.service_types; }).catch(error => { this.error = (error.response && error.response.data.message) || 'Unable to connect to the WhatsApp transaction database.'; }).finally(() => { this.loading = false; }); },
  openOrder(order) { this.selected = order; this.statusForm = { status: order.status, note: '' }; },
  updateStatus() { if (!this.statusForm.note || this.statusForm.note.length < 5) { this.$toasted.show('Enter a clear audit reason.'); return; } this.updating = true; axios.put(`/api/admin/whatsapp-transactions/${this.selected.id}`, this.statusForm).then(response => { this.$toasted.show(response.data.message); this.selected = null; this.load(this.orders.current_page || 1); }).catch(error => { this.$toasted.show((error.response && error.response.data.message) || 'Status update failed.'); }).finally(() => { this.updating = false; }); },
  canRefund(order) { return order && ['PENDING_CONFIRMATION','WAITING_PAYMENT','PAID','PENDING'].indexOf(order.status) >= 0 && (!order.payment || order.payment.status !== 'REFUNDED'); },
  refundOrder() { if (!this.statusForm.note || this.statusForm.note.length < 5) { this.$toasted.show('Enter a clear refund reason.'); return; } if (!confirm('Refund this unsettled transaction to the customer wallet and notify them on WhatsApp?')) return; this.refunding = true; axios.post(`/api/admin/whatsapp-transactions/${this.selected.id}/refund`, { note: this.statusForm.note }).then(response => { this.$toasted.show(response.data.message); this.selected = null; this.load(this.orders.current_page || 1); }).catch(error => { this.$toasted.show((error.response && error.response.data.message) || 'Refund failed. Nothing was changed.'); }).finally(() => { this.refunding = false; }); },
  money(value) { return Number(value || 0).toLocaleString('en-NG', { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }, date(value) { return value ? new Date(value).toLocaleString('en-NG') : '—'; }, humanize(value) { return String(value || '').replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, char => char.toUpperCase()); }, shortId(value) { const text = String(value || ''); return text.length > 12 ? `${text.slice(0, 8)}…` : text; }, customerName(order) { return order.customer && order.customer.name ? order.customer.name : 'WhatsApp Customer'; }, walletPayment(order) { return Number(order.wallet_amount || 0) >= Number(order.amount || 0) ? 'WALLET' : 'NONE'; }, paymentClass(order) { const status = order.payment ? order.payment.status : this.walletPayment(order); return status === 'SUCCESS' || status === 'WALLET' ? 'badge-success' : status === 'FAILED' ? 'badge-danger' : 'badge-warning'; }, statusClass(status) { if (status === 'COMPLETED') return 'complete'; if (['FAILED','CANCELLED','EXPIRED'].indexOf(status) >= 0) return 'failed'; return 'pending'; },
} };
</script>

<style scoped>
.wa-page{padding:22px}.wa-header{display:flex;justify-content:space-between;align-items:center}.wa-header h2{font-weight:800;margin:0}.wa-header p{color:#747983}.summary-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:20px 0}.summary-grid article,.panel{background:#fff;border:1px solid #e8eaed;border-radius:14px;padding:18px}.summary-grid span{display:block;color:#777;font-size:11px;text-transform:uppercase}.summary-grid strong{font-size:23px}.filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:10px;margin-bottom:15px}td small{display:block;color:#80858d}.status{padding:5px 9px;border-radius:18px;font-size:11px;font-weight:800}.status.complete{background:#e5f7ed;color:#14743e}.status.failed{background:#fee9e9;color:#a71919}.status.pending{background:#fff2d8;color:#925d00}.modal-layer{position:fixed;z-index:1050;inset:0;background:rgba(20,25,30,.65);display:grid;place-items:center;padding:20px}.dialog{position:relative;width:min(540px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:16px;padding:25px}.close-button{position:absolute;right:14px;top:8px;border:0;background:none;font-size:28px}.dialog dl{display:grid;grid-template-columns:110px 1fr;gap:7px;margin-top:18px}.dialog dt{color:#777}.dialog label{font-weight:700;margin-top:10px}@media(max-width:950px){.summary-grid{grid-template-columns:repeat(2,1fr)}.filters{grid-template-columns:1fr 1fr}}@media(max-width:600px){.wa-page{padding:12px}.summary-grid,.filters{grid-template-columns:1fr}.wa-header{align-items:flex-start;gap:10px}}
</style>
