<template>
 <main class="sl-service">
  <header class="sl-header"><div><h1>Betting &amp; Travel eSIM</h1><p>Control availability, pricing and transactions.</p></div></header>
  <p v-if="message" class="sl-alert" role="status">{{ message }}</p>
  <form v-if="settings" class="sl-card" @submit.prevent="saveSettings">
   <div class="sl-columns"><section><h2>Betting</h2><label class="sl-toggle"><input type="checkbox" v-model="settings.betting_enabled"><strong>Enable betting funding</strong></label><p class="sl-muted">PayVessel credentials: {{ settings.payvessel_configured?'Configured':'Not configured on the server' }}</p><div class="sl-row sl-between"><label class="sl-field">Enabled betting platforms</label><button type="button" class="sl-btn ghost" :disabled="busy" @click="loadBillers">Load PayVessel Billers</button></div><p class="sl-muted">Select only betting platforms. Other bill types must remain unselected.</p><div v-if="billers.length"><label v-for="b in billers" :key="b.biller_id" class="sl-toggle"><input type="checkbox" v-model="settings.betting_biller_ids" :value="b.biller_id">{{ b.biller_name }} <small class="sl-muted">{{ b.biller_id }}</small></label></div><p v-else>Selected IDs: {{ settings.betting_biller_ids.join(', ')||'None' }}</p></section>
   <section><h2>Travel eSIM</h2><label class="sl-toggle"><input type="checkbox" v-model="settings.esim_enabled"><strong>Enable eSIM purchases and top-ups</strong></label><label for="esim-rate" class="sl-field">Exchange rate — NGN per 1 USD</label><input id="esim-rate" v-model="settings.usd_ngn" type="number" min="0" max="100000" step="0.0001" required class="sl-input"><p class="sl-muted mt-2">Example: a $2 plan at ₦1,500/USD costs ₦3,000. Existing quotes and purchases keep their original price. New quotes use the saved rate.</p><p class="sl-muted">eSIM Access credentials: {{ settings.esim_configured?'Configured':'Not configured on the server' }}</p><p class="sl-muted">Switching off stops new purchases and top-ups. Existing eSIMs, installation codes and pending-payment reconciliation remain accessible.</p></section></div><label for="esim-terms-admin" class="sl-field">eSIM Terms &amp; Conditions</label><textarea id="esim-terms-admin" v-model="settings.esim_terms" class="sl-input" rows="10" maxlength="30000" placeholder="Enter the approved eSIM terms displayed in the pre-purchase popup."></textarea><p class="sl-muted">Plain text. Customers can open these terms before buying in the app and website.</p><button class="sl-btn mt-3" :disabled="busy">{{ busy?'Saving…':'Save Service Settings' }}</button>
  </form>
  <section class="sl-card"><h2>Service Transactions</h2><form class="sl-row my-3" @submit.prevent="loadTransactions(1)"><select v-model="service" class="sl-input sl-grow" aria-label="Service" @change="loadTransactions(1)"><option value="betting">Betting</option><option value="esim">Travel eSIM</option></select><select v-model="status" class="sl-input sl-grow" aria-label="Status"><option value="">All statuses</option><option>pending</option><option>processing</option><option>success</option><option v-if="service==='betting'">failed</option><option v-if="service==='betting'">cancelled</option><option v-if="service==='esim'">reversed</option></select><input class="sl-input sl-grow" v-model.trim="search" placeholder="Reference or customer ID" aria-label="Search transactions"><button class="sl-btn" :disabled="busy">Search</button></form>
   <div class="sl-table-wrap"><table class="sl-table"><thead><tr><th>Reference / Customer</th><th>Service / Account</th><th>Amount</th><th>Rate</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody><tr v-for="r in transactions.data" :key="r.id"><td>{{ r.reference }}<small class="d-block">Customer #{{ r.user_id }}</small></td><td>{{ r.biller_name||r.package_name }}<small class="d-block">{{ r.recharge_account||r.kind }}</small></td><td>{{ money(service==='betting'?r.amount:Number(r.amount_kobo)/100) }}</td><td>{{ r.exchange_rate||'—' }}</td><td>{{ r.status }}<small class="d-block">{{ r.error_code }}</small></td><td>{{ r.created_at }}</td><td><button class="sl-btn ghost" :disabled="busy" @click="recheck(r)">Recheck</button><button v-if="service==='esim'&&r.kind==='topup'&&['pending','processing'].includes(r.status)" class="sl-btn secondary mt-2" @click="resolving=r;evidence='';outcome=''">Resolve Top Up</button></td></tr><tr v-if="!transactions.data?.length"><td colspan="7">No matching transactions.</td></tr></tbody></table></div><div class="sl-row sl-between mt-3"><button class="sl-btn ghost" :disabled="busy||transactions.current_page<=1" @click="loadTransactions(transactions.current_page-1)">Previous</button><span>Page {{ transactions.current_page||1 }} of {{ transactions.last_page||1 }}</span><button class="sl-btn ghost" :disabled="busy||transactions.current_page>=transactions.last_page" @click="loadTransactions(transactions.current_page+1)">Next</button></div>
  </section>
  <section class="sl-card"><div class="sl-row sl-between"><h2>Settings &amp; Resolution Audit</h2><button class="sl-btn ghost" @click="loadAudits">Refresh</button></div><details v-for="a in audits" :key="a.id" class="mt-3"><summary>{{ a.created_at }} · Admin #{{ a.admin_id }}</summary><pre style="white-space:pre-wrap">{{ a.after_values }}</pre></details></section>
  <div v-if="resolving" class="sl-modal-backdrop"><form class="sl-modal" role="dialog" aria-modal="true" @submit.prevent="resolve"><h2>Resolve Top Up</h2><p>Reference: {{ resolving.reference }}</p><p class="sl-alert">Only resolve after eSIM Access confirms the outcome. A reversal returns {{ money(resolving.amount_kobo/100) }} to the customer’s wallet.</p><label class="sl-field">Provider-confirmed outcome<select v-model="outcome" class="sl-input" required><option value="" disabled>Select confirmed outcome</option><option value="success">Delivered successfully</option><option value="reversed">Not delivered — refund customer</option></select></label><label class="sl-field">Provider confirmation / support reference<textarea v-model.trim="evidence" class="sl-input" minlength="15" maxlength="2000" required></textarea></label><button class="sl-btn sl-full mt-3" :disabled="busy">Record Confirmed Outcome</button><button type="button" class="sl-btn ghost sl-full mt-2" :disabled="busy" @click="resolving=null">Cancel</button></form></div>
 </main>
</template>
<script>
import axios from 'axios';
import './service-ui.css';
export default {
 name:'ServiceAdmin',data(){return {settings:null,billers:[],busy:false,message:'',service:'betting',status:'',search:'',transactions:{data:[]},audits:[],resolving:null,outcome:'',evidence:''};},
 async mounted(){try{this.settings=(await axios.get('/api/admin/services/settings')).data.data;}catch(e){this.message=this.error(e);}await Promise.all([this.loadTransactions(1),this.loadAudits()]);},
 methods:{error(e){return e.response?.data?.message||'Request failed. Please try again.';},money(n){return Number(n).toLocaleString('en-NG',{style:'currency',currency:'NGN'});},
 async saveSettings(){this.busy=true;this.message='';try{this.settings=(await axios.put('/api/admin/services/settings',{betting_enabled:this.settings.betting_enabled,esim_enabled:this.settings.esim_enabled,usd_ngn:String(this.settings.usd_ngn),betting_biller_ids:this.settings.betting_biller_ids,esim_terms:this.settings.esim_terms||''})).data.data;this.message='Service settings saved.';await this.loadAudits();}catch(e){this.message=this.error(e);}finally{this.busy=false;}},
 async loadBillers(){this.busy=true;try{this.billers=(await axios.get('/api/admin/services/billers')).data.data;}catch(e){this.message=this.error(e);}finally{this.busy=false;}},
 async loadTransactions(page){try{this.transactions=(await axios.get('/api/admin/services/transactions',{params:{service:this.service,status:this.status,search:this.search,page}})).data.data;}catch(e){this.message=this.error(e);}},
 async loadAudits(){try{this.audits=(await axios.get('/api/admin/services/audits')).data.data.data;}catch(e){this.message=this.error(e);}},
 async recheck(row){this.busy=true;try{await axios.post(`/api/admin/services/${this.service}/${row.id}/recheck`);await this.loadTransactions(this.transactions.current_page);}catch(e){this.message=this.error(e);}finally{this.busy=false;}},
 async resolve(){this.busy=true;try{await axios.post(`/api/admin/services/esim/${this.resolving.id}/resolve`,{outcome:this.outcome,evidence:this.evidence});this.resolving=null;await Promise.all([this.loadTransactions(1),this.loadAudits()]);}catch(e){this.message=this.error(e);}finally{this.busy=false;}},
 },
};
</script>
