<template>
  <main class="sl-service">
    <header class="sl-header"><div><h1>Travel eSIM</h1><p>Stay connected wherever you go.</p></div><i class="fas fa-globe-africa fa-2x" aria-hidden="true"></i></header>
    <div class="sl-tabs"><button :class="{active:tab==='buy'}" @click="tab='buy'">Buy eSIM</button><button :class="{active:tab==='mine'}" @click="tab='mine';loadMine()">My eSIMs</button></div>
    <p v-if="error" class="sl-alert" role="alert">{{ error }}</p>
    <div v-if="attempt" class="sl-alert"><p>Your last purchase needs confirmation.</p><button class="sl-btn" :disabled="busy" @click="purchase">Continue Last Payment</button></div>
    <div v-if="tab==='buy'" class="sl-columns">
      <section>
        <div class="sl-card"><h2>{{ topupProfile ? 'Top Up Your eSIM' : 'Where are you travelling?' }}</h2><p v-if="!enabled" class="sl-alert">New eSIM purchases and top-ups are currently unavailable. Your existing eSIMs remain accessible.</p>
          <template v-if="topupProfile"><p>{{ profileName(topupProfile) }} · {{ topupProfile.details.iccid }}</p><button class="sl-btn ghost" @click="topupProfile=null;plans=[]">Choose a new eSIM</button></template>
          <template v-else><label for="esim-search" class="sl-field">Search destination</label><input id="esim-search" v-model="search" class="sl-input" placeholder="Country or region"><label for="esim-location" class="sl-field">Select destination</label><select id="esim-location" v-model="location" class="sl-input" :disabled="busy || !enabled || !!attempt" @change="loadPlans"><option value="">Choose country or region</option><option v-for="l in filteredLocations" :value="l.code" :key="l.code">{{ flag(l.code) }} {{ l.name }}</option></select></template>
        </div>
        <p v-if="loading" role="status">Loading plans…</p>
        <div class="sl-plan-grid"><article v-for="p in plans" :key="p.package_code" class="sl-card"><h3>{{ p.name }}</h3><p>{{ volume(p.volume) }}{{ p.daily ? ' per day' : '' }} · {{ p.duration }} {{ p.duration_unit.toLowerCase() }}</p><p class="sl-muted">{{ p.speed }} · {{ p.activation_type===2 ? 'Activates on first network connection' : 'Activates on installation' }}</p><p v-if="p.fup_policy" class="sl-muted">Fair use: {{ p.fup_policy }}</p><div class="sl-price">{{ money(p.amount_kobo) }}<small v-if="p.daily" class="sl-muted"> / day</small></div><button class="sl-btn sl-full mt-3" :disabled="busy || !enabled || !!attempt" @click="selectPlan(p)">Choose Plan</button></article></div>
        <p v-if="location && !loading && !plans.length" class="sl-muted">No plans are available for this destination right now.</p>
      </section>
      <aside class="sl-card"><h2>Easy Steps to<br>Stay Connected</h2><ol class="sl-steps"><li>Select destination</li><li>Choose a plan</li><li>Enter PIN &amp; buy</li><li>Get your eSIM</li><li>Install &amp; enjoy</li></ol><p class="sl-muted">Check that your phone supports eSIM and is network-unlocked before purchasing. An internet connection is needed for installation.</p></aside>
    </div>
    <section v-else>
      <div class="sl-row sl-between mb-3"><h2>My eSIMs</h2><button class="sl-btn ghost" :disabled="busy" @click="loadMine">Refresh</button></div>
      <p v-if="!profiles.length" class="sl-card">Your purchased eSIMs will appear here.</p>
      <div class="sl-plan-grid"><article v-for="p in profiles" :key="p.id" class="sl-card"><div class="sl-row sl-between"><h3>{{ flag(p.details.packageList?.[0]?.locationCode) }} {{ profileName(p) }}</h3><span class="sl-status">{{ statusLabel(p.details.esimStatus) }}</span></div><p>{{ volume(p.details.totalVolume) }} · {{ p.details.totalDuration }} days</p><div class="sl-progress"><span :style="{width:remainingPercent(p)+'%'}"></span></div><p>{{ volume(remaining(p)) }} remaining</p><p class="sl-muted">Expires: {{ date(p.details.expiredTime) }}</p><div class="sl-row"><button class="sl-btn ghost sl-grow" @click="openProfile(p)">View Details</button><button v-if="canTopup(p)" class="sl-btn secondary" :disabled="busy || !enabled || !!attempt" @click="topup(p)">Top Up</button></div></article></div>
      <h2 class="mt-4">Recent Purchases</h2><button v-for="p in purchases" :key="p.id" class="sl-btn ghost sl-full mb-2" @click="result=p"><span>{{ p.package_name }} · {{ money(p.amount_kobo) }} · {{ p.status }}</span></button>
    </section>
    <div v-if="selected" class="sl-modal-backdrop" @click.self="!busy && (selected=null)"><section class="sl-modal" role="dialog" aria-modal="true" aria-labelledby="esim-plan-title"><h2 id="esim-plan-title">{{ selected.name }}</h2><p>{{ volume(selected.volume) }}{{ selected.daily?' per day':'' }} · {{ selected.duration }} {{ selected.duration_unit.toLowerCase() }}</p><label v-if="selected.daily" class="sl-field">Number of days<input type="number" v-model="days" min="1" max="365" class="sl-input" @input="quote=null"></label><p class="sl-muted">{{ selected.description }}</p><div v-for="n in selected.networks" :key="n.locationName" class="sl-muted">{{ n.locationName }}: {{ n.operatorList.map(o=>o.operatorName+' '+o.networkType).join(', ') }}</div><label class="sl-toggle"><input type="checkbox" v-model="compatible"><span>My device supports eSIM and is network-unlocked.</span></label><button type="button" class="sl-btn ghost sl-full mb-3" @click="openTerms">Terms &amp; Conditions</button><p v-if="quote" class="sl-price">{{ money(quote.amount_kobo) }}</p><p v-if="error" class="sl-alert">{{ error }}</p><button v-if="!quote" class="sl-btn sl-full" :disabled="busy||!compatible" @click="getQuote">{{ busy?'Getting price…':'Confirm Price' }}</button><button v-else class="sl-btn sl-full" :disabled="busy||!compatible" @click="purchase">Enter PIN &amp; Buy · {{ money(quote.amount_kobo) }}</button><button class="sl-btn ghost sl-full mt-2" :disabled="busy" @click="selected=null">Cancel</button></section></div>
    <div v-if="result" class="sl-modal-backdrop" @click.self="result=null"><section class="sl-modal sl-result" role="dialog" aria-modal="true" aria-labelledby="esim-result-title"><div class="sl-result-icon" :class="result.status">{{ result.status==='success'?'✓':result.status==='reversed'?'×':'◷' }}</div><h2 id="esim-result-title">{{ result.status==='success' ? (result.kind==='topup'?'Top Up Successful':'eSIM Ready!') : result.status==='reversed'?'eSIM Purchase Reversed':'Preparing Your eSIM' }}</h2><p>{{ result.status==='success'?'Your purchase was completed successfully.':result.status==='reversed'?`${money(result.amount_kobo)} has been returned to your wallet.`:'Your payment is pending. Check its status before making another purchase.' }}</p><div class="sl-card">{{ result.package_name }}<p class="sl-price">{{ money(result.amount_kobo) }}</p><small class="sl-muted">{{ result.reference }}</small></div><p v-if="error" class="sl-alert">{{ error }}</p><button v-if="['pending','processing'].includes(result.status)" class="sl-btn sl-full" :disabled="busy" @click="checkResult">Check Status</button><button v-if="result.status==='success'&&result.profile_id" class="sl-btn sl-full mb-2" @click="openResultProfile">Install / View eSIM</button><button class="sl-btn secondary sl-full mt-2" @click="result=null;tab='mine';loadMine()">View in My eSIMs</button><button class="sl-btn ghost sl-full mt-2" @click="result=null">Done</button></section></div>
    <div v-if="detail" class="sl-modal-backdrop" @click.self="detail=null"><section class="sl-modal" role="dialog" aria-modal="true" aria-labelledby="esim-detail-title"><div class="sl-row sl-between"><h2 id="esim-detail-title">eSIM Details</h2><button class="sl-btn ghost" @click="detail=null">Close</button></div><h3>{{ profileName(detail) }}</h3><span class="sl-status">{{ statusLabel(detail.details.esimStatus) }}</span><h3 class="mt-4">Data Remaining</h3><strong>{{ volume(remaining(detail)) }} / {{ volume(detail.details.totalVolume) }}</strong><div class="sl-progress"><span :style="{width:remainingPercent(detail)+'%'}"></span></div><p class="sl-muted">Usage updates may be delayed by 2–3 hours. Last checked: {{ date(detail.synced_at) }}</p><p v-if="detail.stale" class="sl-alert">Live details are unavailable; showing the last saved details.</p><dl class="sl-details"><div><dt>Validity</dt><dd>{{ detail.details.totalDuration }} days</dd></div><div><dt>Expires</dt><dd>{{ date(detail.details.expiredTime) }}</dd></div><div><dt>ICCID</dt><dd>{{ detail.details.iccid }}</dd></div><div><dt>Network</dt><dd>{{ (detail.networks||[]).flatMap(n=>n.operatorList||[]).map(o=>o.operatorName).join(", ")||"See plan coverage" }}</dd></div><div><dt>APN</dt><dd>{{ detail.details.apn||'Automatic' }}</dd></div><div><dt>Installation</dt><dd>{{ detail.details.smdpStatus }}</dd></div></dl><button v-if="canTopup(detail)" class="sl-btn sl-full mb-2" :disabled="busy||!enabled||!!attempt" @click="topup(detail);detail=null">Top Up</button><a v-if="installUrl(detail)" :href="installUrl(detail)" rel="noopener noreferrer" target="_blank" class="sl-btn secondary sl-full mb-2">Install eSIM</a><button class="sl-btn ghost sl-full" @click="showQr=!showQr">{{ showQr?'Hide':'View' }} QR Code</button><div v-if="showQr" class="sl-result mt-3"><img v-if="safeUrl(detail.details.qrCodeUrl)" class="sl-qr" :src="detail.details.qrCodeUrl" alt="Private eSIM installation QR code"><p class="sl-muted">Scan from your phone’s Add eSIM settings. Keep this code private.</p></div><details class="mt-3"><summary>Manual installation</summary><p>On your device, open Settings → Mobile / Cellular → Add eSIM → Enter details manually.</p><p>SM-DP+ Address: <code>{{ activation(detail)[1] }}</code></p><p>Activation Code: <code>{{ activation(detail)[2] }}</code></p><button class="sl-btn ghost" @click="copyActivation">Copy Activation Code</button></details></section></div>
    <div v-if="termsOpen" class="sl-modal-backdrop" style="z-index:10020" @click.self="termsOpen=false"><section class="sl-modal" role="dialog" aria-modal="true" aria-labelledby="esim-terms-heading"><h2 id="esim-terms-heading">Terms &amp; Conditions</h2><div style="white-space:pre-wrap;line-height:1.6">{{ terms }}</div><button class="sl-btn sl-full mt-3" @click="termsOpen=false">Close</button></section></div>
  </main>
</template>
<script>
import axios from 'axios';
import Auth from '../../Auth.js';
import './service-ui.css';
export default {
 name:'TravelEsim',
 data(){return {tab:'buy',locations:[],location:'',search:'',plans:[],profiles:[],purchases:[],enabled:false,loading:false,busy:false,error:'',selected:null,days:1,compatible:false,quote:null,result:null,detail:null,showQr:false,topupProfile:null,attempt:null,termsOpen:false,terms:''};},
 computed:{key(){return `esim_attempt_${Auth.user?.id}`;},filteredLocations(){return this.locations.filter(l=>l.name.toLowerCase().includes(this.search.toLowerCase()));}},
 async mounted(){try{this.attempt=JSON.parse(localStorage.getItem(this.key)||'null');const s=(await axios.get('/api/services/status')).data.data;this.enabled=s.esim_enabled;if(this.enabled)this.locations=(await axios.get('/api/esim/locations')).data.data;}catch(e){this.error=this.message(e);}await this.loadMine();},
 methods:{
  message(e){return e.response?.data?.message||'Unable to connect. Please try again.';},money(k){return (Number(k)/100).toLocaleString('en-NG',{style:'currency',currency:'NGN'});},volume(b){return (Number(b||0)/1073741824).toLocaleString('en-NG',{maximumFractionDigits:2})+' GB';},date(d){return d?new Date(d).toLocaleString():'Not activated';},flag(c){return /^[A-Z]{2}$/.test(c||'')?Array.from(c,x=>String.fromCodePoint(127397+x.charCodeAt(0))).join(''):'🌍';},profileName(p){return p.details.packageList?.[0]?.packageName||'Travel eSIM';},remaining(p){return Math.max(0,Number(p.details.totalVolume||0)-Number(p.details.orderUsage||0));},remainingPercent(p){return Math.min(100,100*this.remaining(p)/Math.max(1,Number(p.details.totalVolume||0)));},statusLabel(s){return {GOT_RESOURCE:'Ready to install',IN_USE:'Active',USED_UP:'Data used',USED_EXPIRED:'Expired',UNUSED_EXPIRED:'Expired',CANCEL:'Cancelled',SUSPENDED:'Suspended'}[s]||s;},canTopup(p){return [2,3].includes(Number(p.details.supportTopUpType))&&!['USED_EXPIRED','UNUSED_EXPIRED','CANCEL','REVOKE'].includes(p.details.esimStatus);},safeUrl(s){try{return new URL(s).protocol==='https:';}catch{return false;}},activation(p){return String(p.details.ac||'').split('$');},installUrl(p){const url=p.details.shortUrl;try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='p.qrsim.net'?u.href:'';}catch{return '';}},
  async openTerms(){this.termsOpen=true;this.terms='Loading terms…';try{this.terms=(await axios.get('/api/esim/terms')).data.data.content||'Terms are not yet published. Please contact support.';}catch{this.terms='Unable to load terms. Please try again before purchasing.';}},
  async loadMine(){try{const [p,h]=await Promise.all([axios.get('/api/esim/profiles'),axios.get('/api/esim/purchases')]);this.profiles=p.data.data;this.purchases=h.data.data;}catch(e){this.error=this.message(e);}},
  async loadPlans(){this.plans=[];if(!this.location&&!this.topupProfile)return;this.loading=true;this.error='';try{this.plans=(await axios.get('/api/esim/packages',{params:this.topupProfile?{profile_id:this.topupProfile.id}:{location:this.location}})).data.data;}catch(e){this.error=this.message(e);}finally{this.loading=false;}},
  selectPlan(p){this.selected=p;this.quote=null;this.days=1;this.compatible=false;this.error='';},
  async getQuote(){this.busy=true;try{const data={package_code:this.selected.package_code,location:this.location};if(this.selected.daily)data.period_num=Number(this.days);if(this.topupProfile)data.profile_id=this.topupProfile.id;this.quote=(await axios.post('/api/esim/quotes',data)).data.data;}catch(e){this.error=this.message(e);}finally{this.busy=false;}},
  async purchase(){if(this.busy)return;this.busy=true;this.error='';try{if(!this.attempt){const bytes=crypto.getRandomValues(new Uint8Array(14));this.attempt={quote_id:this.quote.id,reference:'SLE'+Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')};localStorage.setItem(this.key,JSON.stringify(this.attempt));}const r=(await axios.post('/api/esim/purchases',this.attempt)).data.data;if(!r||!['pending','processing','success','reversed'].includes(r.status))throw new Error('Unconfirmed purchase');this.result=r;this.selected=null;this.quote=null;localStorage.removeItem(this.key);this.attempt=null;await this.loadMine();}catch(e){if(!axios.isCancel(e)){this.error=this.message(e);if([401,403,422,428,429].includes(e.response?.status)){localStorage.removeItem(this.key);this.attempt=null;this.quote=null;}}}finally{this.busy=false;}},
  async checkResult(){this.busy=true;try{this.result=(await axios.get(`/api/esim/purchases/${encodeURIComponent(this.result.reference)}`)).data.data;await this.loadMine();}catch(e){this.error=this.message(e);}finally{this.busy=false;}},
  async openProfile(p){this.detail=p;this.showQr=false;try{this.detail=(await axios.get(`/api/esim/profiles/${p.id}`)).data.data;}catch(e){this.error=this.message(e);}},
  async openResultProfile(){const id=this.result.profile_id;this.result=null;await this.loadMine();const p=this.profiles.find(p=>p.id===id);if(p)await this.openProfile(p);},
  async topup(p){this.topupProfile=p;this.tab='buy';await this.loadPlans();},
  async copyActivation(){try{await navigator.clipboard.writeText(this.detail.details.ac);}catch{this.error='Select and copy the manual installation details.';}},
 },
};
</script>
